name: Docs Deploy

permissions:
  contents: write # needed for the deploy step

on:
  workflow_run:
    workflows: ["Docs Build"]
    types: [completed]
    branches:
      - "main"

jobs:
  docs-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.event == 'push' }}
    environment:
      name: docs-deploy
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Download Artifact
        uses: dawidd6/action-download-artifact@ac66b43f0e6a346234dd65d4d0c8fbb31cb316e5 # v11
        with:
          workflow: docs-build.yml
          name: docs-build
          path: docs/build/

      # Note, the gh-pages deployment requires setting up a SSH deploy key.
      # See
      # https://github.com/JamesIves/github-pages-deploy-action/tree/dev#using-an-ssh-deploy-key-
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4a3abc783e1a24aeb44c16e869ad83caf6b4cc23 # v4.7.4
        with:
          folder: docs/build/
          ssh-key: ${{ secrets.DEPLOY_KEY }}
