name: Docs Deploy

permissions:
  contents: write # needed for the deploy step

on:
  workflow_run:
    workflows: ["Docs Build"]
    types: [completed]
    branches:
      - "main"

jobs:
  docs-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.event == 'push' }}
    environment:
      name: docs-deploy
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Download Artifact
        uses: dawidd6/action-download-artifact@883bc3da0e2f55ddd0a8fc8e99378551c1991a55 # v13
        with:
          workflow: docs-build.yml
          name: docs-build
          path: docs/build/

      # Note, the gh-pages deployment requires setting up a SSH deploy key.
      # See
      # https://github.com/JamesIves/github-pages-deploy-action/tree/dev#using-an-ssh-deploy-key-
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4.8.0
        with:
          folder: docs/build/
          ssh-key: ${{ secrets.DEPLOY_KEY }}
